apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditrcard-auth-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      name: creditrcard-auth-pod
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: registry.gitlab.com/shift-python/y2023/homeworks/shurinova-ya/week3/task1/auth
        ports:
          - containerPort: 24023
        resources:
          limits:
            cpu: 300m
            memory: '1Gi'
          requests:
            cpu: 300m
            memory: '1Gi'
        readinessProbe:
          httpGet:
            path: /ready
            port: 24023
          failureThreshold: 5
          initialDelaySecond: 30
          periodSeconds: 2
          successThreshold: 2
        livenessProbe:
          httpGet:
            path: /live
            port: 24023
          failureThreshold: 10
          initialDelaySecond: 3
          periodSeconds: 2
        env:
          - name: AUTH_URL
            valueFrom:
              configMapKeyRef:
                key: auth_url
                name: creditcard-configmap
          - name: MAIN_URL
            valueFrom:
              configMapKeyRef:
                key: main_url
                name: creditcard-configmap
          - name: VERIFY_URL
            valueFrom:
              configMapKeyRef:
                key: verify_url
                name: creditcard-configmap
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db_password
                name: creditcard-secret