apiVersion: v1
kind: Service
metadata:
  name: creditrcard-auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: {{ .Values.app.servicePort}}
      targetPort: {{ .Values.app.servicePort}}
