apiVersion: v1
kind: Service
metadata:
  name: creditrcard-main-service
spec:
  selector:
    app: main-service
  ports:
    - port: {{ .Values.app.servicePort}}
      targetPort: {{ .Values.app.servicePort}}
