"""empty message

Revision ID: a236e00e7207
Revises: 
Create Date: 2023-10-05 10:53:37.096757

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a236e00e7207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_log',
    sa.Column('balance_log_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=False),
    sa.Column('before', sa.Integer(), nullable=False),
    sa.Column('after', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('balance_log_id')
    )
    op.create_table('common_log',
    sa.Column('common_log_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=True),
    sa.Column('before', sa.String(), nullable=False),
    sa.Column('after', sa.String(), nullable=False),
    sa.Column('changes', sa.String(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('common_log_id')
    )
    op.create_table('log_storage',
    sa.Column('log_storage_id', sa.Integer(), nullable=False),
    sa.Column('balance_log_id', sa.String(length=100), nullable=False),
    sa.Column('common_log_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('log_storage_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('log_storage_id', sa.Integer(), nullable=False),
    sa.Column('user_storage_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('user',
    sa.Column('card_number', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('card_limit', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_table('user_storage',
    sa.Column('user_storage_id', sa.Integer(), nullable=False),
    sa.Column('user_card_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='f', nullable=True),
    sa.ForeignKeyConstraint(['user_card_number'], ['user.card_number'], ),
    sa.PrimaryKeyConstraint('user_storage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_storage')
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('log_storage')
    op.drop_table('common_log')
    op.drop_table('balance_log')
    # ### end Alembic commands ###
